project:
  type: book

book:
  title: "Thoughts and Advice on Writing your BAP"
  author: "Dr. Joshua Robison"
  date: today
  chapters:
    - index.qmd
    - part: part_writing.qmd
      chapters:
      - writing_01_structure.qmd
      - writing_02_introduction.qmd
      - writing_03_review.qmd
      - writing_04_design.qmd
      - writing_05_analyses.qmd
      - writing_06_conclusion.qmd
      - writing_07_general.qmd
    - part: part_research.qmd
      chapters: 
        - doing_01_research.qmd
        - doing_02_data.qmd
    - part: part_analysis.qmd
      chapters: 
        - analysis_01.qmd
        - analysis_02.qmd
        - analysis_rscript.qmd
        - analysis_discussion.qmd
        - analysis_03.qmd
        - analysis_04.qmd
        - analysis_pivot.qmd
        - analysis_robust.qmd
        - analysis_clustering.qmd
        - analysis_mlogit.qmd
        - analysis_ologit.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: darkly

editor: visual

