---
reference-location: margin
---

# Surveys and Experiments in Qualtrics

You have chosen to collect your own survey/experimental data for your BAP thesis. In order to actually do this, though, you will need to create the survey instrument and distribute it to your sample of participants. This section of the book covers that process by providing an overview/introduction to the Qualtrics platform, which is a survey platform that you have access to via your ULCN account. See [here](https://www.staff.universiteitleiden.nl/research/it-and-research/qualtrics/service-units/ict-shared-service-centre?cf=service-units&cd=ict-shared-service-centre){target="_blank"} for more information on gaining access to Qualtrics.

These chapters are introductions and certainly do not cover all use cases or options. Qualtrics also offers an in-depth [support](https://www.qualtrics.com/support/){target="_blank"} page that may be of help if you're running into an issue or want to learn more. Indeed, I will often provide links to relevant sections of their support pages in the discussions to come.

You will probably rely on existing questions when creating your survey (i.e., taking question wordings from existing survey sources). If you're thinking of writing your own questions, then see [this resource](https://web.stanford.edu/dept/communication/faculty/krosnick/docs/1999/1999%20Maximizing%20questionnaire%20quality.pdf){target="_blank"} from Jon Krosnick that discusses research on the various properties of questions that may make them better/worse. [Berinsky](https://catalogue.leidenuniv.nl/permalink/31UKB_LEU/rdnp04/cdi_crossref_citationtrail_10_1146_annurev_polisci_101513_113724) offers a nice overall discussion as well with a particular focus on political science surveys and on the important role of specificity and question wording.

It is a good idea to read (some of) this [this book](https://catalogue.leidenuniv.nl/permalink/31UKB_LEU/rdnp04/cdi_proquest_ebookcentral_EBC7029093){target="_blank"} by Druckman on "experimental thinking" to think about why we experiment and how to do so as well as we can.
