---
reference-location: margin
---

# Research Design/Data Section {#sec-research-designdata-section}

## Goals

This section of your thesis has a fairly straightforward goal: telling your reader why your analyses take the form that they do (e.g., why this data, why these measurements, why this model, etc.). I have noticed that students often structure this section in very...interesting ways. So, I will discuss how best to structure this area of your thesis and some other supplemental points below.

## Basic Structure

Here is a general guideline on how to structure this section:

-   Data: Where does the data come from/how was it created?
-   Dependent Variable: How are you operationalizing your dependent variable(s) using this data?
-   Main Independent Variable(s): How are you operationalizing your main independent variable(s), i.e., the predictor variable(s) specified in your hypothesis/hypotheses? This also covers a discussion of any moderators although you should discus the main IV first and then the moderator.
-   Model and Controls: How are you actually going to test your hypothesis/es? What variables are you including as controls while doing so (and why them)?

This structure is my general recommendation and it should apply to nearly all theses in my BAP. However, I could see some room for deviations in situations where multiple data sources are being used in the analyses. The above, for instance, works great if you're using data from something like the World Values Survey or European Social Survey by itself. But, your particular project may require a combination of datasets. If this involves simply adding some data to an existing survey dataset (e.g., merging data on economic growth from the World Bank into your European Social Survey dataset), then I would keep the general structure the same as above and talk about the source of the added data when you introduce the variable in question (e.g., in the Main Independent Variables or Control variable sections).[^writing_04_design-1] On the other hand, your project may require you to combine multiple databases together into a wholly new data source.[^writing_04_design-2] If that were the case, then I would skip the first bit on Data and discuss the source of each variable as you introduce it.

[^writing_04_design-1]: See the Statistics I R Book for how to "join" datasets ([weblink](https://poweleiden.github.io/statistics1/data_06_merging_data.html#joining-data-sets){target="_blank"}).

[^writing_04_design-2]: As an example, a student in a prior year wrote a BAP predicting hate crime prevalence in the United States based on economic conditions and various other predictors. The student combined data on hate crimes from the US Department of Justice, data on economic conditions from another source, and so on, into a new dataset.

Note: It generally makes sense to have these discussions as separate subsections with bolded section headers. See @sec-writing-structure for an example.

## Some More Specific Points

### Discuss(ing) how the data was generated

You are probably using a secondary data source: the American National Election Studies, the World Values Survey, and so on. Per the structure above, you should probably begin this section of the thesis by telling your reader(s) about this data source. A stronger discussion here goes beyond simply saying "I'm using ANES data" to tell the reader a little bit more about how the data was actually generated by the people running these surveys. How as the sample generated? (Probability-based sample? Convenience?) How were people interviewed? (In-person? By phone? Online?). When was the data collected specifically?

The answers to some of these questions may be important for understanding your results and potentially their limitations when it comes to generalization. For instance, perhaps the survey is done using a face to face interview. If so, are any of your core variables "[sensitive items](https://catalogue.leidenuniv.nl/permalink/f/1cnfioc/TN_cdi_apa_psycarticles_bul_133_5_859){taget="_blank"}" that may invite (some) people to hide their true preferences due to social desirability pressures? If so, then then what does that mean for your results? Does it make it *easier* or *harder* to find evidence consistent with your hypothesis(es)?

Building on this last point, you will want to discuss potential "limitations" with your data and how they may affect your results (see also, @sec-conclusion). Where should those discussions occur? I would generally say that it is okay to preview this discussion in this section of the paper with a fuller one in the Conclusion since you will want to incorporate into this discussion some thoughts on how the "limitation" in question might be addressed by other researchers (and what might happen if they did so).

### Assumption checks

You should check the assumptions underlying the particular model that you are using. The results of these assumption checks can be presented in an Appendix (which does not count against your overall word count) and referenced in the Model and Controls sub-section. I would recommend not bogging this discussion down with too much detail about the procedures you took and their results as you can leave that for the Appendix. Instead, you would want to clearly and efficiently communicate that you checked the assumptions and (1) they all more/less checked out so you did not need to take any additional steps or (2) you identified some issue, in which case you'd note how you updated or altered your statistical model to address it (e.g., the inclusion of a squared term, you used some other type of standard error, etc.).

An additional point about this Appendix: you should include an actual discussion of the results of your assumption checks. In other words, don't just plop down some graphs or tables and leave them as is, but instead also include a short interpretation of those results. Treat the assumptions appendix much you would the analyses in text - with polished tables/graphs and clear discussions.

### Talking about models and control variables

You should tell your reader how you are analyzing your DV.

The first component of this discussion is a note regarding the specific type of statistical model that you are using and why you have chosen this one. This generally does not require very much elaboration as the type of analysis is going to be determined the nature of your DV (i.e., continuous DV = OLS, binary = logistic). So, a simple proviso is all most of you will need: "I use an \[model\] because my dependent variable is \[scale\]". Of course, your specific project may use other types of data that may entail some other modeling strategy. Maybe your DV is categorical in which case you need something like a multinomial logistic model (see **SECTION** for more on this). Perhaps you have a "clustered" dataset, in which case you would need to do something to deal with that and make a note of what that "something" happens to be (see **SECTION** for more on this topic).

You also need to tell the reader what else (besides your main IVs of interest) is going into this model to predict the DV. In particular, you need to tell the reader what you are controlling for in your model(s) and sufficient information about how they are coded/scaled so that your reader can understand your regression output. In general, I would recommend leaving the in-depth details about the measurement (e.g. question wording) and coding of control variables to an Appendix with a reference to this appendix in the main-text. It's still a good idea to have some mention of the direction of the variable's coding in the main text (e.g., higher values on the variable = ?) though. This information could be a simple bullet point list like so:

-   Ideology
    -   Respondents were asked the following question: "In general, how do you place yourself on this scale from 0-10 where 0 = left, 10 = right" (mean = X; SD = X).
-   Education
    -   Respondents were asked to indicate the highest level of education that they had finished with the following options: (1) less than secondary education; (2) secondary; (3) tertiary; (4) etc. I created a binary version of this variable where 0 = less than secondary (X%) and secondary and 1 = tertiary and post-collegiate degrees (X%).
-   Variable 3
    -   Details

The idea here is to give the reader sufficient information so that they can understand your model without bogging down the discussion with potentially superfluous details. The appendix is one way to thread that needle.

As an additional point here, it makes sense to include a short point about *why* you are including these particular variables as controls. That is, justify their inclusion in some way. Typically, we control for variables to reduce bias in our models - we are worried that the relationship between our main variable of interest and the DV is actual spurious in nature because this relationship occurs due the correlation between them and confounding variables. A justification on this front may highlight a reason (such as previous studies) suggesting that the control might cause *both* the DV and the main IV of interest in the model with a reference to relevant work to give warrant to the claim.

I discuss additional questions and issues in relation to statistical modeling that you may encounter in the final section of this book.

### Don't use SPSS/R variable names in-text

You may be tempted to refer in text to one of your variables by the name you gave it in R (e.g. something like "lrscale" to capture ideology). Do not do this. You are only forcing your reader to remember more things and do more work, which in the process may confuse matters for them. More work for a reader means a more disagreeable reader. Instead, refer to the concepts that these variables are trying to measure or operationalize.

Another version of this is the tendency to talk about the minute procedures you undertook to analyze the data, e.g. importing the data into R from an .csv file or something like that. Unless these procedures required some out of the ordinary effort this is almost certainly unnecessary as it is unlikely to convey any useful information. Don't waste words!

### Provide descriptive data!

When you have your data ready to analyze you will probably want to just jump straight into multivariate models. Resist this temptation. Instead, get to know your data. How much variation is there in your key variables? Are they skewed? Are there potential outliers? What are the bivariate relationships between your core variables (and particularly your main IV and the DV)? Doing so may help you identify potential issues that you will need to address as well as giving you a deeper understanding of your data that can help you better discuss you results.

When you turn to writing your research design and results sections, it is a good idea to present/discuss *some* of these descriptive results to give the reader a sense of the underlying data, although avoid bogging the discussion down with too many minute details. At the very least, you should provide some descriptive data about your main IV(s), any moderator, and your DV. This would typically focus on their mean and measure of dispersion (e.g., standard deviation or confidence interval for continuous variables) or frequencies (for binary or categorical variables). This could also include some bivariate analyses (e.g., contingency tables, correlations), although bivariate analyses between your main variables may be more useful as the start of the analyses section.

How should you present this data? Simple summary statistics about a variable can often be communicated in-text. For instance, you might write something like:

> We use two questions as dependent variables. First, respondents were asked about their level of democratic satisfaction ("how satisfied are you with the way democracy is working in \[country name\]") with four response options (very satisfied, somewhat satisfied, not too satisfied, and not at all satisfied). We rescaled this variable to range from 0-1 with higher values indicating more democratic satisfaction (mean = 0.518 \[95% CI: 0.513, 0.522\]). Second, respondents were asked whether their country's political system "needs to be completely reformed, needs major changes, needs minor changes, or doesn't need to be changed". We use this question as an indicator for system legitimacy. We rescaled this measure to range from 0-1 but here higher values indicate support for changing the system and hence lower legitimacy (mean = 0.599 \[0.594, 0.603\]).

You could alternatively provide this information in a table or graph (boxplot, histogram, etc.) as well.
