<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Thoughts and Advice on Writing your BAP - 13&nbsp; Discussing Your Model Results</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./analysis_03.html" rel="next">
<link href="./analysis_rscript.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">

<script src="site_libs/tabwid-1.1.3/tabwid.js"></script>


  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./part_analysis.html">Practical Issues in Data Analysis</a></li><li class="breadcrumb-item"><a href="./analysis_discussion.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Discussing Your Model Results</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Thoughts and Advice on Writing your BAP</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part_writing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Writing the Thesis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./writing_01_structure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Structuring the Thesis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./writing_02_introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./writing_03_review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Review of Literature and Argument</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./writing_04_design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Research Design/Data Section</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./writing_05_analyses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Results/Analyses Section</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./writing_06_conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./writing_07_general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">General Writing Advice</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part_research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Doing Research</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./doing_01_research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Finding Literature</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./doing_02_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Finding and Evaluating Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practical Issues in Data Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Analysis Steps</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Some Practical Questions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_rscript.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">R Script Files</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_discussion.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Discussing Your Model Results</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Regression Table Formatting Suggestion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Combining Plots</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_pivot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Reshaping Datasets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_robust.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Heteroskedasticity and Robust Standard Errors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis_clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Geographically Clustered/Nested Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#example-model-and-some-initial-thoughts" id="toc-example-model-and-some-initial-thoughts" class="nav-link active" data-scroll-target="#example-model-and-some-initial-thoughts"><span class="header-section-number">13.1</span> Example Model and Some Initial Thoughts</a></li>
  <li><a href="#two-questions-to-think-about-for-substantive-significance" id="toc-two-questions-to-think-about-for-substantive-significance" class="nav-link" data-scroll-target="#two-questions-to-think-about-for-substantive-significance"><span class="header-section-number">13.2</span> Two Questions to Think About for Substantive Significance</a></li>
  <li><a href="#ols-model-factor-predictor" id="toc-ols-model-factor-predictor" class="nav-link" data-scroll-target="#ols-model-factor-predictor"><span class="header-section-number">13.3</span> OLS Model, Factor Predictor</a></li>
  <li><a href="#ols-model-continuous-predictor" id="toc-ols-model-continuous-predictor" class="nav-link" data-scroll-target="#ols-model-continuous-predictor"><span class="header-section-number">13.4</span> OLS Model, Continuous Predictor</a></li>
  <li><a href="#logistic-model" id="toc-logistic-model" class="nav-link" data-scroll-target="#logistic-model"><span class="header-section-number">13.5</span> Logistic Model</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./part_analysis.html">Practical Issues in Data Analysis</a></li><li class="breadcrumb-item"><a href="./analysis_discussion.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Discussing Your Model Results</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-discussing-your-model-results" class="quarto-section-identifier"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Discussing Your Model Results</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="annotated-cell-1"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-1-1"><a href="#annotated-cell-1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Packages</span></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="1">1</button><span id="annotated-cell-1-2" class="code-annotation-target"><a href="#annotated-cell-1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(flextable)</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="2">2</button><span id="annotated-cell-1-3" class="code-annotation-target"><a href="#annotated-cell-1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary)</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="3">3</button><span id="annotated-cell-1-4" class="code-annotation-target"><a href="#annotated-cell-1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="4">4</button><span id="annotated-cell-1-5" class="code-annotation-target"><a href="#annotated-cell-1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rio)</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="5">5</button><span id="annotated-cell-1-6" class="code-annotation-target"><a href="#annotated-cell-1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="6">6</button><span id="annotated-cell-1-7" class="code-annotation-target"><a href="#annotated-cell-1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="7">7</button><span id="annotated-cell-1-8" class="code-annotation-target"><a href="#annotated-cell-1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(parameters)</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="8">8</button><span id="annotated-cell-1-9" class="code-annotation-target"><a href="#annotated-cell-1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="annotated-cell-1-10"><a href="#annotated-cell-1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-1-11"><a href="#annotated-cell-1-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Data &amp; some data cleaning</span></span>
<span id="annotated-cell-1-12"><a href="#annotated-cell-1-12" aria-hidden="true" tabindex="-1"></a>demdata <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="st">"./data/demdata.rds"</span>) <span class="sc">|&gt;</span> </span>
<span id="annotated-cell-1-13"><a href="#annotated-cell-1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="9">9</button><span id="annotated-cell-1-14" class="code-annotation-target"><a href="#annotated-cell-1-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">regime_type_2006 =</span> <span class="fu">case_when</span>(</span>
<span id="annotated-cell-1-15"><a href="#annotated-cell-1-15" aria-hidden="true" tabindex="-1"></a>      Typeregime2006 <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>) <span class="sc">~</span> <span class="st">"Democracy (2006)"</span>, </span>
<span id="annotated-cell-1-16"><a href="#annotated-cell-1-16" aria-hidden="true" tabindex="-1"></a>      Typeregime2006 <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"Autocracy (2006)"</span>), </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="10">10</button><span id="annotated-cell-1-17" class="code-annotation-target"><a href="#annotated-cell-1-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">regime_type_2006 =</span> <span class="fu">factor</span>(regime_type_2006,</span>
<span id="annotated-cell-1-18"><a href="#annotated-cell-1-18" aria-hidden="true" tabindex="-1"></a>                              <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Democracy (2006)"</span>, </span>
<span id="annotated-cell-1-19"><a href="#annotated-cell-1-19" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"Autocracy (2006)"</span>)))</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-1" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="2" data-code-annotation="1">Table formatting</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="3" data-code-annotation="2">Regression tables</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="4" data-code-annotation="3">Predicted values, marginal effects, comparisons</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="5" data-code-annotation="4">Data importing/exporting</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="5">5</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="6" data-code-annotation="5">Data manipulation &amp; plotting</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="6">6</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="7" data-code-annotation="6">Combining plots</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="7">7</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="8" data-code-annotation="7">Standardized coefficients</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="8">8</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="9" data-code-annotation="8">Model summaries</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="9">9</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="14" data-code-annotation="9">Creates a binary variable comparing countries deemed some type of democracy (liberal dem [1] or electoral dem [2]) vs.&nbsp;countries deemed an autocracy (3).</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="10">10</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="17" data-code-annotation="10">Converts that binary variable into a factor. Democracies are treated as the ‘baseline’ or ‘reference’ group (as if = 0) against which autocracies (=1) will be compared).</span>
</dd>
</dl>
</div>
</div>
<p>A thesis in my BAP will almost certainly use some type of regression model (OLS, logit, etc.) to summarize the relationship between multiple predictor variables and a dependent variable. The likely goal of this model is to examine some hypothesis, e.g., Y is expected to increase when X increases holding other predictors “constant”. You naturally need some tools for communicating the results of that model, and particularly the results relevant to your hypothesis, to your readers. On the one hand, you should include a regression table and/or a coefficient plot (with a regression table in an appendix) in the main body of the thesis. On the other hand, you need to include some written explanation of what the results show in relation to your hypothesis/es.</p>
<p>A natural place to focus your written explanation of the model is on the coefficient for the independent variable(s) central to your hypothesis/es. And, indeed, that was the focus of the instructions you were given in Statistics II about how to talk about regression results. However, you should go beyond talking about the direction (i.e., positive or negative) and statistical significance of this coefficient in your thesis to better flesh out what the model is telling us. In particular, you want to leave your reader with some sense of the <em>substantive</em> relationship between the two variables. Is this a “meaningful” association or not?</p>
<p>This chapter provides some thoughts on how you can can use your model to better flesh out discussions regarding this important, but difficult, question.</p>
<section id="example-model-and-some-initial-thoughts" class="level2 page-columns page-full" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="example-model-and-some-initial-thoughts"><span class="header-section-number">13.1</span> Example Model and Some Initial Thoughts</h2>
<p>Let’s consider an initial model:</p>
<div class="cell" data-tbl-cap-location="top">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="annotated-cell-2"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-2-1"><a href="#annotated-cell-2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># OLS Model </span></span>
<span id="annotated-cell-2-2"><a href="#annotated-cell-2-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(v2x_polyarchy <span class="sc">~</span> Women2003 <span class="sc">+</span> GDP2006 <span class="sc">+</span> regime_type_2006, </span>
<span id="annotated-cell-2-3"><a href="#annotated-cell-2-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> demdata)</span>
<span id="annotated-cell-2-4"><a href="#annotated-cell-2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-5"><a href="#annotated-cell-2-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Table (See Chapter 'Regression Table Formatting Suggestion' </span></span>
<span id="annotated-cell-2-6"><a href="#annotated-cell-2-6" aria-hidden="true" tabindex="-1"></a><span class="do">## for reasoning behing this syntax)</span></span>
<span id="annotated-cell-2-7"><a href="#annotated-cell-2-7" aria-hidden="true" tabindex="-1"></a><span class="do">## I do not specify a Title here because I am doing that behind </span></span>
<span id="annotated-cell-2-8"><a href="#annotated-cell-2-8" aria-hidden="true" tabindex="-1"></a><span class="do">## the scenes in creating this html document</span></span>
<span id="annotated-cell-2-9"><a href="#annotated-cell-2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-10"><a href="#annotated-cell-2-10" aria-hidden="true" tabindex="-1"></a>dem_models <span class="ot">&lt;-</span> <span class="fu">modelsummary</span>(m1, </span>
<span id="annotated-cell-2-11"><a href="#annotated-cell-2-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">estimate =</span> <span class="st">"{estimate}{stars}</span><span class="sc">\n</span><span class="st">({std.error})"</span>, </span>
<span id="annotated-cell-2-12"><a href="#annotated-cell-2-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">statistic =</span> <span class="cn">NULL</span>, </span>
<span id="annotated-cell-2-13"><a href="#annotated-cell-2-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">gof_map =</span> <span class="fu">c</span>(<span class="st">"nobs"</span>, <span class="st">"r.squared"</span>, <span class="st">"adj.r.squared"</span>), </span>
<span id="annotated-cell-2-14"><a href="#annotated-cell-2-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">coef_rename =</span> <span class="fu">c</span>(</span>
<span id="annotated-cell-2-15"><a href="#annotated-cell-2-15" aria-hidden="true" tabindex="-1"></a>               <span class="st">'(Intercept)'</span> <span class="ot">=</span> <span class="st">'Intercept'</span>, </span>
<span id="annotated-cell-2-16"><a href="#annotated-cell-2-16" aria-hidden="true" tabindex="-1"></a>               <span class="st">'Women2003'</span> <span class="ot">=</span> <span class="st">'% Women MPs (2003)'</span>, </span>
<span id="annotated-cell-2-17"><a href="#annotated-cell-2-17" aria-hidden="true" tabindex="-1"></a>               <span class="st">'GDP2006'</span> <span class="ot">=</span> <span class="st">'GDP Per Capita (2006)'</span>, </span>
<span id="annotated-cell-2-18"><a href="#annotated-cell-2-18" aria-hidden="true" tabindex="-1"></a>               <span class="st">'regime_type_2006Autocracy (2006)'</span> <span class="ot">=</span> <span class="st">'Autocracy in 2006? (1 = Yes, 0 = Democracy)'</span>), </span>
<span id="annotated-cell-2-19"><a href="#annotated-cell-2-19" aria-hidden="true" tabindex="-1"></a>             <span class="at">notes =</span> <span class="fu">list</span>(<span class="st">"Notes: OLS or Logit Coefficients with standard errors in parentheses"</span>, </span>
<span id="annotated-cell-2-20"><a href="#annotated-cell-2-20" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"* p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001"</span>), </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="1">1</button><span id="annotated-cell-2-21" class="code-annotation-target"><a href="#annotated-cell-2-21" aria-hidden="true" tabindex="-1"></a>             <span class="at">fmt =</span> <span class="fu">fmt_term</span>(<span class="at">GDP2006 =</span> <span class="st">"%.3e"</span>),</span>
<span id="annotated-cell-2-22"><a href="#annotated-cell-2-22" aria-hidden="true" tabindex="-1"></a>             <span class="at">output =</span> <span class="st">'flextable'</span> )</span>
<span id="annotated-cell-2-23"><a href="#annotated-cell-2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-24"><a href="#annotated-cell-2-24" aria-hidden="true" tabindex="-1"></a>dem_models <span class="ot">&lt;-</span> dem_models <span class="sc">|&gt;</span> </span>
<span id="annotated-cell-2-25"><a href="#annotated-cell-2-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hline</span>(<span class="at">i =</span> <span class="fu">nrow_part</span>(dem_models) <span class="sc">-</span> <span class="dv">3</span>) <span class="sc">|&gt;</span>  </span>
<span id="annotated-cell-2-26"><a href="#annotated-cell-2-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">align</span>(<span class="at">i =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow_part</span>(dem_models), <span class="at">j =</span> <span class="dv">2</span><span class="sc">:</span><span class="fu">ncol_keys</span>(dem_models), </span>
<span id="annotated-cell-2-27"><a href="#annotated-cell-2-27" aria-hidden="true" tabindex="-1"></a>        <span class="at">align =</span> <span class="st">'center'</span>) <span class="sc">|&gt;</span>  </span>
<span id="annotated-cell-2-28"><a href="#annotated-cell-2-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">align</span>(<span class="at">align =</span> <span class="st">'center'</span>, <span class="at">part =</span> <span class="st">'header'</span>) <span class="sc">|&gt;</span> </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="2">2</button><span id="annotated-cell-2-29" class="code-annotation-target"><a href="#annotated-cell-2-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autofit</span>()</span>
<span id="annotated-cell-2-30"><a href="#annotated-cell-2-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-31"><a href="#annotated-cell-2-31" aria-hidden="true" tabindex="-1"></a>dem_models</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-2" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-2" data-code-lines="21" data-code-annotation="1">The coefficient for GDP will be very small given its coding. This bit of syntax handles the rounding of values for this specific coefficient value. The coefficient is small enough that the default would be to simply print “0.000***” absent this line. See <a href="https://modelsummary.com/vignettes/modelsummary.html#fmt" target="_blank">here</a> for more.</span>
</dd>
<dt data-target-cell="annotated-cell-2" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-2" data-code-lines="29" data-code-annotation="2">This makes the table fit the columns of the page. It works well with html output and okay when exporting to Word.</span>
</dd>
</dl>
</div>
<div id="tbl-dem-model" class="cell quarto-float anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dem-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.1: Predicting Democracy Levels
</figcaption>
<div aria-describedby="tbl-dem-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-bcc4b11a{}.cl-bcba0210{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-bcbe090a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bcbe0914{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bcbe2002{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bcbe200c{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bcbe2016{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bcbe2017{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bcbe2018{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bcbe2020{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bcbe202a{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bcbe202b{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bcbe2034{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bcbe2035{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bcbe2036{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bcbe2037{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bcbe203e{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bcbe203f{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bcbe2048{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bcbe2049{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-bcc4b11a"><thead><tr style="overflow-wrap:break-word;"><th class="cl-bcbe2002"><p class="cl-bcbe090a"><span class="cl-bcba0210"> </span></p></th><th class="cl-bcbe200c"><p class="cl-bcbe090a"><span class="cl-bcba0210">(1)</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-bcbe2016"><p class="cl-bcbe0914"><span class="cl-bcba0210">Intercept</span></p></td><td class="cl-bcbe2017"><p class="cl-bcbe090a"><span class="cl-bcba0210">0.475***</span><br><span class="cl-bcba0210">(0.027)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bcbe2016"><p class="cl-bcbe0914"><span class="cl-bcba0210">% Women MPs (2003)</span></p></td><td class="cl-bcbe2017"><p class="cl-bcbe090a"><span class="cl-bcba0210">0.005**</span><br><span class="cl-bcba0210">(0.002)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bcbe2018"><p class="cl-bcbe0914"><span class="cl-bcba0210">GDP Per Capita (2006)</span></p></td><td class="cl-bcbe2020"><p class="cl-bcbe090a"><span class="cl-bcba0210">7.736e-06***</span><br><span class="cl-bcba0210">(1.466e-06)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bcbe202a"><p class="cl-bcbe0914"><span class="cl-bcba0210">Autocracy in 2006? (1 = Yes, 0 = Democracy)</span></p></td><td class="cl-bcbe202b"><p class="cl-bcbe090a"><span class="cl-bcba0210">-0.310***</span><br><span class="cl-bcba0210">(0.035)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bcbe2034"><p class="cl-bcbe0914"><span class="cl-bcba0210">Num.Obs.</span></p></td><td class="cl-bcbe2035"><p class="cl-bcbe090a"><span class="cl-bcba0210">152</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bcbe2036"><p class="cl-bcbe0914"><span class="cl-bcba0210">R2</span></p></td><td class="cl-bcbe2037"><p class="cl-bcbe090a"><span class="cl-bcba0210">0.550</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bcbe203e"><p class="cl-bcbe0914"><span class="cl-bcba0210">R2 Adj.</span></p></td><td class="cl-bcbe203f"><p class="cl-bcbe090a"><span class="cl-bcba0210">0.541</span></p></td></tr></tbody><tfoot><tr style="overflow-wrap:break-word;"><td colspan="2" class="cl-bcbe2048"><p class="cl-bcbe0914"><span class="cl-bcba0210">Notes: OLS or Logit Coefficients with standard errors in parentheses</span></p></td></tr><tr style="overflow-wrap:break-word;"><td colspan="2" class="cl-bcbe2048"><p class="cl-bcbe0914"><span class="cl-bcba0210">* p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</span></p></td></tr></tfoot></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>The DV in the model is a country’s score on the <code>v2x_polyarchy</code> measure of electoral democracy in the year 2020 provided by the Varieties of Democracy (V-Dem) project. The IVs include the following predictor variables: (1) the % of female members of parliament in the country in the year 2003; (2) the country’s gross domestic product per capita in the year 2006; and (3) a binary measure concerning whether the country was considered a democracy (=1) or an autocracy (=0) in the year 2006.</p>
<p>What do the coefficients tell us about the relationship between the predictor variables and the DV?</p>
<ul>
<li>% Women MPs
<ul>
<li>Countries with more female MPs in the year 2003 are, on average, more democratic in the year 2020 than countries with fewer female MPs in 2003.</li>
<li>We expect democracy scores to increase by 0.005 scale points with each one unit (here, 1 %) increase in female MPs after adjusting for differences in country wealth and regime status.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> This relationship is statistically significant (p &lt; 0.01).</li>
</ul></li>
<li>GDP Per Capita (2006)
<ul>
<li>Richer countries are, on average, more democratic in the year 2020 than poorer countries. We expect democracy scores to increase by approximately 7.7359493^{-6} scale points, on average, when a country’s GDP per capita increases by 1 USD after adjusting for differences in female representation and 2006 regime status. This relationship is statistically significant (p &lt; 0.001).</li>
</ul></li>
<li>Autocracy in 2006?
<ul>
<li>Countries that were autocratic in 2006 remain less democratic in 2020 than countries that were democracies in 2006 after adjusting for differences in female representation and country wealth. If we compared countries with the same wealth in 2006 and same female representation in 2003, we’d expect the average democracy score in 2020 to be around -0.31 scale points lower in 2006 autocracies than 2006 democracies.</li>
</ul></li>
</ul>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;If the goal of the model were to examine this variable in particular, then the two “control” variables here might be problematic given that they are based on measurements taken three years after the Women MPs measure. The main question we’d have to consider is whether it is plausible that having more/less female MPs causes a country to have a higher GDP and/or to influence its subsequent regime status (and particularly so on such a small time scale). The latter possibility may be particularly problematic given that our DV is…regime status (e.g., level of democracy)! If the % of female MPs in 2003 does in fact cause variation in 2020 democracy scores and does so in part because of its influence on wealth and/or 2006 regime status, then our estimate for % of female MPs in 2003 will be “biased” - it will almost certainly be smaller than it should be. See the discussion in <a href="analysis_02.html" class="quarto-xref"><span>Chapter 11</span></a>. I am just using these variables because I have them laying around, but if I were actually writing this as a paper then I’d be worried.</p></div></div><p>Okay…but are these differences actually meaningful? The numbers look small in some cases…but we’re dealing with continuous variables that may vary quite greatly, so it’s not clear whether the overall impact is meaningless or not. Consider the following descriptive data and histograms of the two continuous predictors:</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Descriptive Data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>demdata <span class="sc">|&gt;</span> <span class="fu">select</span>(GDP2006, Women2003) <span class="sc">|&gt;</span> </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  psych<span class="sc">::</span><span class="fu">describe</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>          vars   n    mean       sd median trimmed     mad min     max   range
GDP2006      1 165 7148.13 10635.06 2172.0 4847.22 2765.05  93 54779.0 54686.0
Women2003    2 152   14.13     9.60   11.3   13.22    8.38   0    45.3    45.3
          skew kurtosis     se
GDP2006   1.92     3.15 827.94
Women2003 0.85     0.20   0.78</code></pre>
</div>
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plots</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(demdata, <span class="fu">aes</span>(<span class="at">x =</span> GDP2006)) <span class="sc">+</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">'white'</span>, <span class="at">color =</span> <span class="st">'black'</span>) <span class="sc">+</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"GDP Per Capita (2006)"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(demdata, <span class="fu">aes</span>(<span class="at">x =</span> Women2003)) <span class="sc">+</span> </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">'white'</span>, <span class="at">color =</span> <span class="st">'black'</span>) <span class="sc">+</span> </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"% Female MPs in 203"</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">+</span> p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-cont-distribution" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cont-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="analysis_discussion_files/figure-html/fig-cont-distribution-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cont-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.1: Continuous Predictor Variables - Distribution
</figcaption>
</figure>
</div>
</div>
</div>
<p>Okay, so a 1 dollar increase in GDP yields a very small increase in the democracy score. But…is a change of 1 dollar a meaningful comparison to make or care about? The GDP variable ranges from 93 to around 54,779 with a standard deviation of 10,635 after all. A dollar increase in GDP may be meaningful in some instances, but is it what best communicates the influence of country wealth in this one? Meanwhile, the % Female MPs measure also varies quite a bit more than by 1% albeit not as greatly as GDP (e.g,. SD = 9.6 vs.&nbsp;10,635!). The point here is that our unstandardized coefficient tells us something relevant (e.g., the slope of a regression line when the predictor variable is continuous), but we may not want to rely solely on it to convey the <em>importance</em> of the changes on offer.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn2"><p><sup>2</sup>&nbsp;As I’ll discuss below, the coeficient for a binary/categorical variable is perhaps more directly relevant here since these types of variables involve comparisons between two (and only two) groups in the first place.</p></div></div><p>Maybe we can turn to <em>standardized</em> coefficients then?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># DV and IV are standardized by 1 SD</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">standardize_parameters</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Standardization method: refit

Parameter                           | Std. Coef. |         95% CI
-----------------------------------------------------------------
(Intercept)                         |       0.27 | [ 0.15,  0.40]
Women2003                           |       0.20 | [ 0.08,  0.32]
GDP2006                             |       0.32 | [ 0.20,  0.44]
regime type 2006 [Autocracy (2006)] |      -1.22 | [-1.48, -0.95]</code></pre>
</div>
</div>
<p>The standardized coefficients fro <code>Women2003</code> and <code>GDP2006</code> tell us how many standard deviations we expect the DV to change when the IV in question changes by 1 standard deviation. The standardized coefficient for the regime type factor variable, meanwhile, indicate the difference between the two categories of the factor variable (Autocracy in 2006 vs.&nbsp;Democracy in 2006) in standard deviations. We could perhaps now turn to some ‘rules of thumb’ about effect sizes (such as those reported in the <a href="https://poweleiden.github.io/statistics1/analysis_08_t-test.html#effect-sizes-for-t-tests" target="_blank">Statistics I</a> materials for interpreting Cohen’s d) to make claims about the size of these relationships. The two continuous variables might thus be described as having a somewhat small effect, while the regime comparison yields a large one. However…have we really clarified things for ourselves or for those to whom we are communicated our results? What does a 0.2 or 0.32 or 1.22 SD change really mean in our given context? It seems like a lot…but are we talking about a change from a complete autocracy to a complete democracy? From an autocracy to a slightly less autocratic (but still not democratic) country? Something else?<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> Moreover, what if our results were from a logistic model? Technically we can use an odds ratio there, but those aren’t particularly intuitive in their own right either.</p>
<div class="no-row-height column-margin column-container"><div id="fn3"><p><sup>3</sup>&nbsp;The DV is also being standardized here (e.g., 1 SD change in X yields some amount of change in SDs of Y). We could omit that by including <code>include_response = F</code> in our syntax. That might make our discussions easier to follow in situations where the scale of the DV is easier or more intuitive to understand.</p></div></div><p><img src="images/oratio.png" class="img-fluid"></p>
<p>Saying something about the substantive effect of a variable can be difficult as discussed in <a href="writing_05_analyses.html" class="quarto-xref"><span>Chapter 5</span></a>. My recommendation here is to <em>use your model</em>. In particular, use the model to estimate predicted values, i.e., what value we would expect the DV to be, on average, given this model for some important values of your main IV(s). You can then integrate that information into your written reports directly and/or in relation to figures. Doing so will help flesh out what your coefficient is really implying about the relationship and, hence, give greater substance to your discussion.</p>
</section>
<section id="two-questions-to-think-about-for-substantive-significance" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="two-questions-to-think-about-for-substantive-significance"><span class="header-section-number">13.2</span> Two Questions to Think About for Substantive Significance</h2>
<p>The foregoing is a recommendation about the <em>form</em> of how you discuss your results: remind the reader about what your hypothesis, indicate what evidence would be consistent with it in your model, tell us whether that evidence shows up (e.g., is the coefficient in the right direction and statistically significant, and then use predicted values to flesh out the meaning of that coefficient and particularly so in contexts where the coefficient is statistically significant). However, this still elides the question about whether the patterns you see are <em>meaningfully</em> or <em>substantively</em> significant or not. This is a difficult to answer question because the answer may be research question and contingent (e.g., a “small” effect could be meaningful in some contexts but not others). However, I think you should consider two questions on this front to try and structure your discussion and interpretations.</p>
<p>First, what comparison in terms of X values do you want to call our attention to? In other words, if you’re calculating predicted values or creating a predicted values plot, then what would a meaningful difference in X even be in your context?</p>
<p>This question is pretty straight forward to answer if your main IV is a factor variable: the comparison of interest is between the two categories of your binary variable or the reference group and the other categories (or, potentially one or two particular categories) of your categorical variable.</p>
<p>The answer to this question is perhaps less clear cut with a continuous IV. Per above, the coefficient for a continuous variable tells us about change in Y given a one unit change in X, but one unit may or may not be meaningful or important on its own right in particular examples. A 1 dollar difference in GDP seems somewhat trivial…but should we instead be comparing countries that differ by 100 USD, 1000 USD, 50,000 USD? You can (maybe should) provide a plot showing predicted values across the full range of GDP. That may nicely demonstrate the extent of change when moving from the minimum of X to its maximum…but maybe those values are outliers…so, is <em>that</em> the most important comparison to make? This is a question that you’ll need to give consideration in the context of your particular project and data. I’ll discuss some options below.</p>
<p>Second, once you have thought through what a meaningful comparison would be and provided some evidence about the difference in Y in that comparison, you then have to answer the question: “okay, but is the amount of difference important?”. Is it a “big” difference or not? This is a difficult question to answer since the answer can be question and data contingent. Some differences may be <em>prima facie</em> large: for instance, if the difference between “low” and “high” values of X is 8 scale ponits on a variable that ranges from 0 to 10 then, yeah, that’s probably a really large effect. Most of the time, however, you’ll probably not be finding differences of this magnitude. Here are three other ways of considering this question:</p>
<ul>
<li>Percent change and intuition
<ul>
<li>One could use a <a href="https://www.calculatorsoup.com/calculators/algebra/percent-change-calculator.php" target="_blank">calculator</a> (or R as a calculator) to calculate the percentage change represented by a given comparison.</li>
<li>The predicted democracy score for a country with 0 female legislators is 0.53 while it is 0.77 for a country with the maximum observed value on this variable. That yields a percentage change of: <span class="math inline">\(\frac{0.77 - 0.53)}{0.77} * 100 = 31.2\%\)</span></li>
<li>It’s up to intuition, perhaps, from there: does a 31.2% change seem large? It does to me actually…although it’s possible that the difference I’ve brought attention to here (maximum IV - minimum IV) might be unrepresentative. The third quartile for the Women MP variable is 19.5, for instance, so the maximum value seems like an outlier.</li>
</ul></li>
<li>Variation in the DV
<ul>
<li>One could alternatively look at the difference in comparison to the variation in the DV.</li>
<li>One way to do this is to compare the change to the length or range of the DV. For instance, <a href="https://doi.org/10.1111/ajps.12012" target="_blank">Malhotra, Margalit, and Mo</a> consider whether experiencing an economic threat from immigration is associated with greater opposition to immigration. They note on p.&nbsp;401 of their manuscript that the difference in means on their DV between those not threatened and those threatened ranges from 0.06 to 0.12. Their DV is scaled from 0-1. They thus write: “These differences are also substantially meaningful, representing about 6 to 12% of the length of the scale.”
<ul>
<li>This type of discussion can be aided by first converting all non-factor variables used in an OLS model to a 0-1 scale as these authors do. This can be most easily done using the <code>rescale()</code> function in the <code>scales</code> package. For instance: <code>mutate(newvar = scales::rescale(oldvar, to = c(0,1)))</code>. If that is done, then the resulting coefficients automatically compare the difference in the expected mean of Y between those at the maximum of the IV (=1) and those at the minimum (=0). One could then multiply by 100% to get to a similar discussion as the authors above.</li>
</ul></li>
<li>Alternatively, one could use the standard deviation of the DV to give some context here. Suppose that our DV ranges from 0-100 and that we compare observations at the maximum and minimum of an IV where we find an expected difference of 45.8 scale points. Suppose that the standard deviation of the DV is 30.24. The difference between predicted values at the maximum and minimum values of the IV is thus something like 1.5 standard deviations ( <span class="math inline">\(\frac{45.8}{30.24}=1.51\)</span>). That seems like a pretty sizable difference to me!
<ul>
<li>This is similar to the standardized coefficients above, but we are choosing what values of the IV to compare.</li>
</ul></li>
<li>Of course, one must also try and interpret such results as best one can as to whether it is ‘large’ or ‘meaningful’ in the context of the study.</li>
</ul></li>
<li>Change in Status
<ul>
<li>A more qualitative approach. Does the difference in predictions show a change in status of some type? For instance, does moving across the range of the IV lead to a change in the nature of attitudes (e.g., from support to oppose?; from satisfaction to dissatisfaction?; from being unlikely to vote for Candidate A to being more likely than not to vote for Candidate A?).</li>
</ul></li>
</ul>
<p>The remaining sections walk through a few examples and discuss these issues further. They also introduce a command from the <code>marginaleffects</code> package that may help you on the way: the <code>comparisons()</code> function.</p>
</section>
<section id="ols-model-factor-predictor" class="level2 page-columns page-full" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="ols-model-factor-predictor"><span class="header-section-number">13.3</span> OLS Model, Factor Predictor</h2>
<p>Let’s begin with perhaps the simplest example: your main IV is a factor variable (i.e., a binary variable or a categorical variable converted into a factor in R).<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> We’ll use the example from above that features a binary indicator for whether a country was considered an autocracy in the year 1984 or a democracy in that year.</p>
<div class="no-row-height column-margin column-container"><div id="fn4"><p><sup>4</sup>&nbsp;If you’re using SPSS, then you need to manually create the separate dummy variables and include the appropriate number of them in the model. You need to include k-1 dummies where k = the number of categories on the original variable. A variable with four categories (e.g., North, West, South, and East) would necessitate the inclusion of three dummy variables (e.g., <code>north</code> (0 = not North, 1 = North), <code>west</code> (0 = not West, 1 = West), and <code>south</code> (0 = not South, 1 = South).</p></div></div><div class="cell">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-bd607726{}.cl-bd5624e2{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-bd59d7e0{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bd59d7f4{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bd59eb54{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd59eb5e{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd59eb5f{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd59eb68{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd59eb69{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd59eb6a{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd59eb72{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd59eb73{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd59eb74{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd59eb7c{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd59eb7d{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd59eb7e{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd59eb7f{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd59eb86{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd59eb90{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bd59eb9a{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-bd607726"><thead><tr style="overflow-wrap:break-word;"><th class="cl-bd59eb54"><p class="cl-bd59d7e0"><span class="cl-bd5624e2"> </span></p></th><th class="cl-bd59eb5e"><p class="cl-bd59d7e0"><span class="cl-bd5624e2">(1)</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-bd59eb5f"><p class="cl-bd59d7f4"><span class="cl-bd5624e2">Intercept</span></p></td><td class="cl-bd59eb68"><p class="cl-bd59d7e0"><span class="cl-bd5624e2">0.475***</span><br><span class="cl-bd5624e2">(0.027)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bd59eb5f"><p class="cl-bd59d7f4"><span class="cl-bd5624e2">% Women MPs (2003)</span></p></td><td class="cl-bd59eb68"><p class="cl-bd59d7e0"><span class="cl-bd5624e2">0.005**</span><br><span class="cl-bd5624e2">(0.002)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bd59eb69"><p class="cl-bd59d7f4"><span class="cl-bd5624e2">GDP Per Capita (2006)</span></p></td><td class="cl-bd59eb6a"><p class="cl-bd59d7e0"><span class="cl-bd5624e2">7.736e-06***</span><br><span class="cl-bd5624e2">(1.466e-06)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bd59eb72"><p class="cl-bd59d7f4"><span class="cl-bd5624e2">Autocracy in 2006? (1 = Yes, 0 = Democracy)</span></p></td><td class="cl-bd59eb73"><p class="cl-bd59d7e0"><span class="cl-bd5624e2">-0.310***</span><br><span class="cl-bd5624e2">(0.035)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bd59eb74"><p class="cl-bd59d7f4"><span class="cl-bd5624e2">Num.Obs.</span></p></td><td class="cl-bd59eb7c"><p class="cl-bd59d7e0"><span class="cl-bd5624e2">152</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bd59eb7d"><p class="cl-bd59d7f4"><span class="cl-bd5624e2">R2</span></p></td><td class="cl-bd59eb7e"><p class="cl-bd59d7e0"><span class="cl-bd5624e2">0.550</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bd59eb7f"><p class="cl-bd59d7f4"><span class="cl-bd5624e2">R2 Adj.</span></p></td><td class="cl-bd59eb86"><p class="cl-bd59d7e0"><span class="cl-bd5624e2">0.541</span></p></td></tr></tbody><tfoot><tr style="overflow-wrap:break-word;"><td colspan="2" class="cl-bd59eb90"><p class="cl-bd59d7f4"><span class="cl-bd5624e2">Notes: OLS or Logit Coefficients with standard errors in parentheses</span></p></td></tr><tr style="overflow-wrap:break-word;"><td colspan="2" class="cl-bd59eb90"><p class="cl-bd59d7f4"><span class="cl-bd5624e2">* p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</span></p></td></tr></tfoot></table></div>
</div>
</div>
<p>Let’s say that we have the following hypothesis: “Hypothesis 1: Countries considered autocratic in 2006 remain less democratic in 2020 than countries considered democratic in 2006, all else equal”. We might begin our discussion as so:<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn5"><p><sup>5</sup>&nbsp;References to table/figure numbers is, of course, a bit arbitrary here.</p></div></div><div class="page-columns page-full"><blockquote class="blockquote">
<p>I argued in Hypothesis 1 that countries considered autocratic in 2006 would remain less democratic in 2020 than countries considered democratic in 2006. Table 2 shows the results of my regression model where a negative coefficient for 2006 regime type would represent evidence consistent with H1. And, indeed, we see a negative and statistically significant (p &lt; 0.001) coefficient emerge for regime type. Autocratic countries in 2006 are expected to score 0.31 scale points lower on V-Dem’s polyarchy measure than 2006 democratic countries with equivalent levels of female representation and GDP per capita. The evidence in Table 2 is thus consistent with my expectations.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
</blockquote><div class="no-row-height column-margin column-container"><div id="fn6"><p><sup>6</sup>&nbsp;A note here: don’t say that you have “proven” your hypothesis. We don’t really do that. We may falsify them, but evidence consistent with our expectations do not mean that we have definitely proven our claims. Maybe our model is garbage, for instance. Maybe it only applies to our given context.</p></div></div></div>
<p>The foregoing is a very nice discussion: it clearly delineates what the expectations are, what evidence would be consistent with them, and whether that is the case. However, I think we can go a bit further to flesh this out per earlier discussions. In particular, we might use the <code>predictions()</code> command to calculated average predicted values of the DV and then integrate them into our written discussion either directly or by a reference to an additional figure we create.</p>
<p>Here are the predicted values for the two categories of this variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>predvals <span class="ot">&lt;-</span> <span class="fu">predictions</span>(m1, </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="st">"regime_type_2006"</span>, </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">newdata =</span> <span class="st">"mean"</span>) </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>predvals</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 regime_type_2006 Estimate Std. Error     z Pr(&gt;|z|)    S 2.5 % 97.5 %
 Democracy (2006)    0.604     0.0160 37.80   &lt;0.001  Inf 0.573  0.636
 Autocracy (2006)    0.294     0.0303  9.73   &lt;0.001 71.9 0.235  0.354
 Women2003 GDP2006
      14.1    7067
      14.1    7067

Columns: rowid, regime_type_2006, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, Women2003, GDP2006, v2x_polyarchy 
Type:  response </code></pre>
</div>
</div>
<p>And, here is them plotted out:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(predvals, <span class="fu">aes</span>(<span class="at">x =</span> regime_type_2006, </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> estimate)) <span class="sc">+</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> conf.low, </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">ymax =</span> conf.high)) <span class="sc">+</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(estimate, <span class="dv">2</span>)), </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Regime Type (2006)"</span>, </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Predicted 2020 Democracy Score"</span>) <span class="sc">+</span> </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_discussion_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>These values may help us further communicate the substantive importance of this difference. On the one hand, the difference seems quite large when we consider it in relation to the theoretical range of the DV: 0-1. The difference between the two categories is thus around <span class="math inline">\(\frac{1}{3}\)</span> of the DV’s scale.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> Or, we could compare this difference to the standard deviation of the DV (0.25): <span class="math inline">\(\frac{0.31}{0.25} = 1.2\)</span>. What about qualitatively? The V-Dem scale ranges from 0-1 with higher values = more democratic regime, but the specific values (0.3, 0.7, etc.) are a bit abstract as to what they actually represent.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> Democracy score data from Freedom House and elsewhere is often measured on an interval scale and then categorized. <a href="https://www.cogitatiopress.com/politicsandgovernance/article/view/1214" target="_blank">Lührmann, Tannenberg, and Lindberg</a> discuss doing so for the V-Dem measure used here and suggest the regimes must have at least a 0.5 on this <code>v2x_polyarchy</code> variable to be considered democratic. Based on this, we might say that 2006 classifications remain pretty stable or consistent: countries considered autocratic in 2006 remain autocratic (on average) while countries considered democratic in 2006 remain democratic (on average).</p>
<div class="no-row-height column-margin column-container"><div id="fn7"><p><sup>7</sup>&nbsp;In practice, this variable ranges from 0.015 to 0.908 since there are no perfect (non)democracies.</p></div><div id="fn8"><p><sup>8</sup>&nbsp;You can read more about V-Dem’s methodology <a href="https://www.v-dem.net/about/v-dem-project/methodology/" target="_blank">here</a>.</p></div></div><p>We might thus update our discussion to make some of these points salient. (Note: it might make sense to divide this into two paragraphs.)</p>
<blockquote class="blockquote">
<p>I argued in Hypothesis 1 that countries considered autocratic in 2006 would remain less democratic in 2020 than countries considered democratic in 2006. Table 2 shows the results of my regression model where a negative coefficient for 2006 regime type would represent evidence consistent with H1. And, indeed, we see a negative and statistically significant (p &lt; 0.001) coefficient emerge for regime type. The difference between these countries is not just statistically significant, but also substantively meaningful. A difference of 0.31 scale points is around 1/3rd of the scale of the dependent variable. Figure 1, meanwhile, shows the predicted democracy score for each set of countries: 0.29 [95% CI; 0.24, 0.34] in 2006 autocracies and 0.60 [0.57, 0.64] in 2006 democracies. <a href="https://www.cogitatiopress.com/politicsandgovernance/article/view/1214" target="_blank">Lührmann, Tannenberg, and Lindberg</a> recommend a score of 0.5 as a cut off point separating democracies from non-democracies on this measure. The results in Table 2 and Figure 1 thus indicate not just a different in degree, but also a difference in kind with previously autocratic countries remaining autocratic, on average, and previously democratic countries doing the same. Ultimately, the evidence in Table 2 is thus consistent with my expectations.</p>
</blockquote>
</section>
<section id="ols-model-continuous-predictor" class="level2 page-columns page-full" data-number="13.4">
<h2 data-number="13.4" class="anchored" data-anchor-id="ols-model-continuous-predictor"><span class="header-section-number">13.4</span> OLS Model, Continuous Predictor</h2>
<p>Okay, let’s consider a situation where our IV is continuous in nature such as the % Women MPs measure in this example:</p>
<div class="cell">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-bdb5395a{}.cl-bdaa2402{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-bdae6026{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bdae603a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-bdae75d4{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bdae75de{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bdae75e8{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bdae75e9{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bdae75f2{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bdae75fc{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bdae75fd{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bdae75fe{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bdae7606{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bdae7607{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bdae7608{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bdae7610{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bdae7611{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bdae7612{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bdae761a{width:3.376in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-bdae761b{width:1.152in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-bdb5395a"><thead><tr style="overflow-wrap:break-word;"><th class="cl-bdae75d4"><p class="cl-bdae6026"><span class="cl-bdaa2402"> </span></p></th><th class="cl-bdae75de"><p class="cl-bdae6026"><span class="cl-bdaa2402">(1)</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-bdae75e8"><p class="cl-bdae603a"><span class="cl-bdaa2402">Intercept</span></p></td><td class="cl-bdae75e9"><p class="cl-bdae6026"><span class="cl-bdaa2402">0.475***</span><br><span class="cl-bdaa2402">(0.027)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bdae75e8"><p class="cl-bdae603a"><span class="cl-bdaa2402">% Women MPs (2003)</span></p></td><td class="cl-bdae75e9"><p class="cl-bdae6026"><span class="cl-bdaa2402">0.005**</span><br><span class="cl-bdaa2402">(0.002)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bdae75f2"><p class="cl-bdae603a"><span class="cl-bdaa2402">GDP Per Capita (2006)</span></p></td><td class="cl-bdae75fc"><p class="cl-bdae6026"><span class="cl-bdaa2402">7.736e-06***</span><br><span class="cl-bdaa2402">(1.466e-06)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bdae75fd"><p class="cl-bdae603a"><span class="cl-bdaa2402">Autocracy in 2006? (1 = Yes, 0 = Democracy)</span></p></td><td class="cl-bdae75fe"><p class="cl-bdae6026"><span class="cl-bdaa2402">-0.310***</span><br><span class="cl-bdaa2402">(0.035)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bdae7606"><p class="cl-bdae603a"><span class="cl-bdaa2402">Num.Obs.</span></p></td><td class="cl-bdae7607"><p class="cl-bdae6026"><span class="cl-bdaa2402">152</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bdae7608"><p class="cl-bdae603a"><span class="cl-bdaa2402">R2</span></p></td><td class="cl-bdae7610"><p class="cl-bdae6026"><span class="cl-bdaa2402">0.550</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-bdae7611"><p class="cl-bdae603a"><span class="cl-bdaa2402">R2 Adj.</span></p></td><td class="cl-bdae7612"><p class="cl-bdae6026"><span class="cl-bdaa2402">0.541</span></p></td></tr></tbody><tfoot><tr style="overflow-wrap:break-word;"><td colspan="2" class="cl-bdae761a"><p class="cl-bdae603a"><span class="cl-bdaa2402">Notes: OLS or Logit Coefficients with standard errors in parentheses</span></p></td></tr><tr style="overflow-wrap:break-word;"><td colspan="2" class="cl-bdae761a"><p class="cl-bdae603a"><span class="cl-bdaa2402">* p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</span></p></td></tr></tfoot></table></div>
</div>
</div>
<p>Let’s say that we have the following hypothesis: “Hypothesis 1: Countries with greater female representation are more democratic than countries with less female representation, all else equal”. We might begin our discussion as so:</p>
<blockquote class="blockquote">
<p>I argued in Hypothesis 1 that countries female representation would be positively associated with democracy levels. Table 2 shows the results of my regression model where a positive coefficient for female representation would represent evidence consistent with H1. And, indeed, there is a positive and statistically significant (p &lt; 0.01) coefficient emerge for this variable. Each one percentage increase in female representation is associated with an increase of 0.005 scale points, on average, after adjusting for differences in country wealth and prior regime status. The evidence in Table 2 is thus consistent with my expectations.</p>
</blockquote>
<p>Again, not bad. But, 0.005 seems awfully small. Is this actually a meaningful comparison?</p>
<p>One place we could begin is by plotting expected democracy scores across the range of our continuous predictor variable. We could then produce a plot showing these results in our paper to anchor our discussions. We’ll first use the <code>predictions()</code> command to obtain sensible values of the IV to obtain predictions for and then return to the command to get the average predictions for each level:<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn9"><p><sup>9</sup>&nbsp;We could just do <code>summary(demdata$Women2003)</code> to get these values. The risk here concerns missing data - if our model is only done on a subset of observations in our full dataset due to missing data on either the DV or one of the other IVs, then the minimum and maximum values might not match those used in fitting the model.</p></div></div><div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Range of IV via predictions() among observations in model</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predictions</span>(m1) <span class="sc">|&gt;</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Women2003) <span class="sc">|&gt;</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Women2003     
 Min.   : 0.000  
 1st Qu.: 7.675  
 Median :11.300  
 Mean   :14.130  
 3rd Qu.:19.550  
 Max.   :45.300  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Get the predicted values</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>predvals_cont <span class="ot">&lt;-</span> <span class="fu">predictions</span>(m1, </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">newdata =</span> <span class="fu">datagrid</span>(<span class="at">Women2003 =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">7.7</span>, <span class="fl">14.1</span>, <span class="fl">19.6</span>, <span class="fl">45.3</span>)))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>predvals_cont</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Women2003 Estimate Std. Error    z Pr(&gt;|z|)     S 2.5 % 97.5 % GDP2006
       0.0    0.529     0.0276 19.2   &lt;0.001 269.6 0.475  0.584    7067
       7.7    0.570     0.0190 30.0   &lt;0.001 654.3 0.533  0.608    7067
      14.1    0.604     0.0160 37.8   &lt;0.001   Inf 0.573  0.636    7067
      19.6    0.634     0.0182 34.9   &lt;0.001 881.7 0.598  0.669    7067
      45.3    0.770     0.0520 14.8   &lt;0.001 162.2 0.668  0.872    7067
 regime_type_2006
 Democracy (2006)
 Democracy (2006)
 Democracy (2006)
 Democracy (2006)
 Democracy (2006)

Columns: rowid, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, GDP2006, regime_type_2006, Women2003, v2x_polyarchy 
Type:  response </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot them</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(predvals_cont, </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Women2003, <span class="at">y =</span> estimate)) <span class="sc">+</span> </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> conf.low, </span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ymax =</span> conf.high), <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span> </span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="dv">16</span>) <span class="sc">+</span> </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Predicted Democracy Score (2020)"</span>, </span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"% Female MPs (2003)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_discussion_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The figure suggests a pretty sizable change in the DV moving across the full range of the IV. Our expectation among countries with 0% female legislators and mean/modal values on the control variables is 0.53 [0.48, 0.58], right around the 0.5 cut off discussed above. The expected values at the observed maximum of the IV is 0.77 [0.67, 0.87], more clearly democratic in nature. The difference between those values represents a 31% change, or a difference equivalent to around 1/3rd of the range of the DV, or a difference of around 0.96 standard deviations or so on the DV. This would indicate a pretty sizable difference.</p>
<p>Including a plot like the one above into our paper would be a great way of fleshing out the meaning of our IV. However, is drawing attention to the difference between minimum and maximum values of this IV really the best comparison in this example? Consider again the distribution of the variable:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_discussion_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The maximum value here seems like a clear outlier. There is only one country at the maximum and the next closest values are at around 37 or so on the scale. The focus on the maximum - minimum might thus overstate the importance of this variable a bit.</p>
<p>Comparing values at the minimum and maximum of a continuous IV may be an intuitive way of conveying the cumulative or total effect of the variable. But, per above, it might not always be appropriate if this change is uncommon or represents differences between outliers. An alternative tactic that you may observe in researcher is to focus on other indicators for “low” and “high” values on a scale that stop short at the very extremes. Common examples include:</p>
<ul>
<li>The 10th and 90th percentiles of the variable’s distribution</li>
<li>The 25th and 75th percentiles of the variable’s distribution</li>
<li>1 standard deviation below and 1 standard deviation above the mean</li>
</ul>
<p>There isn’t really a “right” answer as to which to use. Alternative numbers could be useful as well. Could we imagine a policy intervention, for instance, that leads to a change from 4% (10th percentile) female MPs to 28% female MPs? If not, then maybe a narrower interval would be more useful. Then again, perhaps gender quotas might have such an effect! Or, maybe the comparison of moving from 0% female MPs to average levels might be even more useful. There are no easy answers here but to think about your RQ, the data before you, and what might be particularly useful to draw attention to.</p>
<p>Let’s return to our data. We can find the 25th and 75th quartiles via the <code>summary()</code> command. We can use the <code>quantile()</code> command, meanwhile to obtain percentiles at any other value we might care about.</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-11"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-11-1"><a href="#annotated-cell-11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary()</span></span>
<span id="annotated-cell-11-2"><a href="#annotated-cell-11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(demdata<span class="sc">$</span>Women2003)</span>
<span id="annotated-cell-11-3"><a href="#annotated-cell-11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-11-4"><a href="#annotated-cell-11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># percentiles</span></span>
<span id="annotated-cell-11-5"><a href="#annotated-cell-11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(demdata<span class="sc">$</span>Women2003, </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-11" data-target-annotation="1">1</button><span id="annotated-cell-11-6" class="code-annotation-target"><a href="#annotated-cell-11-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.2</span>, <span class="fl">0.25</span>, <span class="fl">0.75</span>, <span class="fl">0.8</span>, <span class="fl">0.9</span>),</span>
<span id="annotated-cell-11-7"><a href="#annotated-cell-11-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">na.rm =</span> T)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-11" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-11" data-code-lines="6" data-code-annotation="1">Put the percentiles here, but as decimals (e.g., 10th percentile <span class="math inline">\(\rightarrow\)</span> 0.1, etc.).</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   7.675  11.300  14.130  19.550  45.300      27 
   10%    20%    25%    75%    80%    90% 
 3.830  6.040  7.675 19.550 21.480 28.300 </code></pre>
</div>
</div>
<p>Let’s say we think drawing attention to a “low” value of the 10th percentile (3.8% female MPs) and the 90th percentile (28.3%) would best convey the importance of our variable. I would still provide the corresponding full figure of predicted values from above, but I would supplement the text discussion with predicted values at these levels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predictions</span>(m1, </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">newdata =</span> <span class="fu">datagrid</span>(<span class="at">Women2003 =</span> <span class="fu">c</span>(<span class="fl">3.83</span>, <span class="fl">28.3</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Women2003 Estimate Std. Error    z Pr(&gt;|z|)     S 2.5 % 97.5 % GDP2006
      3.83     0.55     0.0229 24.0   &lt;0.001 419.5 0.505  0.595    7067
     28.30     0.68     0.0276 24.6   &lt;0.001 443.0 0.626  0.734    7067
 regime_type_2006
 Democracy (2006)
 Democracy (2006)

Columns: rowid, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, GDP2006, regime_type_2006, Women2003, v2x_polyarchy 
Type:  response </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>I argued in Hypothesis 1 that countries female representation would be positively associated with democracy levels. Table 2 shows the results of my regression model where a positive coefficient for female representation would represent evidence consistent with H1. And, indeed, there is a positive and statistically significant (p &lt; 0.01) coefficient emerges for this variable such that each one percentage increase in female representation is associated with an increase of 0.005 scale points, on average, after adjusting for differences in country wealth and prior regime status. The evidence in Table 2 is thus consistent with my expectations.</p>
<p>How important is the relationship between female representation and subsequent democracy scores? Figure 1 plots the democracy score we expect to observe across the range of female representation. The difference between predicted democracy scores at the maximum observed value for female representation (45.3%) and the observed minimum (0%) is quite substantial in nature (0.24 scale points or approximately one quarter of the range of the DV). However, the the maximum here is bit unrepresentative as only one country in the model has a female representation value above 40%. If we instead compare countries at the 90th (28.3% female representation) and 10th (3.83%) percentiles, then we’d expect to see a difference in democracy scores of 0.13 scale point on average (10th percentile: 0.55 [95% CI: 0.51, 0.60], 90th percentile: 0.68 [0.63, 0.73]). This still represents a fairly important difference. <a href="https://www.cogitatiopress.com/politicsandgovernance/article/view/1214" target="_blank">Lührmann, Tannenberg, and Lindberg</a>, for instance, recommend using 0.5 as the cut off between democratic and non-democratic countries. Moving from a country with very little female representation to one with a comparatively high level (but equivalent values on the other predictor variables) thus represents a change from countries straddling the democracy/non-democracy line to ones that are more consistently democratic in nature.</p>
</blockquote>
<p>There is one final tool that may be relevant here. The discussion above notes the predicted value and its corresponding uncertainty. It also mentions the difference between predicted values. However, this discussion lacks any mention of uncertainty. We can use the <code>comparisons()</code> command in the <code>marginaleffects</code> package to accomplish this end (see <a href="https://marginaleffects.com/vignettes/comparisons.html" target="_blank">here</a> for a longer discussion).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>example_comparison <span class="ot">&lt;-</span> <span class="fu">comparisons</span>(m1, </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">variables =</span> <span class="fu">list</span>(<span class="at">Women2003 =</span> <span class="fu">c</span>(<span class="fl">3.83</span>, <span class="fl">28.3</span>)), </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">newdata =</span> <span class="st">'mean'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<dl>
<dt><code>comparisons(m1,</code></dt>
<dd>
<p>The name of the command is <code>comparisons()</code>. We then provide the name of the saved model object (<code>m1</code> in this example.</p>
</dd>
<dt><code>variable = list(Women2003 = c(3.83, 28.3)),</code></dt>
<dd>
<p>We can then specify which variable the comparison should be done for and the values on that variable we want to compare. In essence, the command will use this information to calculated predicted values at these two levels of the IV and then calculate the <em>difference</em> between them.</p>
</dd>
<dt><code>newdata = 'mean')</code></dt>
<dd>
<p>This tells the command to hold the other predictor variables constant at their mean (continuous variable) or mode (categorical). Omitting this portion of the syntax would not really change things if the model is a linear regression like here - the slope of a linear regression line for a given IV in the model is the same regardless of the specific values of the other predictors. However, this is not the case with a logistic model.</p>
</dd>
</dl>
<p>Let’s take a look at the results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>example_comparison</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      Term    Contrast Estimate Std. Error    z Pr(&gt;|z|)    S  2.5 % 97.5 %
 Women2003 28.3 - 3.83     0.13     0.0389 3.34   &lt;0.001 10.2 0.0536  0.206
 Women2003 GDP2006 regime_type_2006
      14.1    7067 Democracy (2006)

Columns: rowid, term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted, Women2003, GDP2006, regime_type_2006, v2x_polyarchy 
Type:  response </code></pre>
</div>
</div>
<ul>
<li>Term: This indicates the variable in the comparison.</li>
<li>Contrast: This indicates the type of comparison being offered. Here, we specified that we wanted to look at the difference in predicted value between cases with a value of 28.3 on the <code>Women2003</code> IV and those with a value of 3.83, hence “28.3 - 3.83”.</li>
<li>Estimate: The difference between the predicted values. 0.13 much as above.</li>
<li>Std. Error, z, Pr(&gt;|Z|), 2.5%, and 97.%: The standard error, test-statistic, p-value for the comparison, and confidence intervals. You can ignore the “s” column.</li>
</ul>
<p>The difference in predicted values here is 0.13 [95% CI: 0.05, 0.21] and statistically significant (p &lt; 0.001). This might be helpful information to convey in the written report:</p>
<blockquote class="blockquote">
<p>I argued in Hypothesis 1 that countries female representation would be positively associated with democracy levels. Table 2 shows the results of my regression model where a positive coefficient for female representation would represent evidence consistent with H1. And, indeed, there is a positive and statistically significant (p &lt; 0.01) coefficient emerges for this variable such that each one percentage increase in female representation is associated with an increase of 0.005 scale points, on average, after adjusting for differences in country wealth and prior regime status. The evidence in Table 2 is thus consistent with my expectations.</p>
<p>How important is the relationship between female representation and subsequent democracy scores? Figure 1 plots the democracy score we expect to observe across the range of female representation. The difference between predicted democracy scores at the maximum observed value for female representation (45.3%) and the observed minimum (0%) is quite substantial in nature (0.24 scale points or approximately one quarter of the range of the DV). However, the the maximum here is bit unrepresentative as only one country in the model has a female representation value above 40%. If we instead compare countries at the 90th (28.3% female representation) and 10th (3.83%) percentiles, then we’d expect to see a difference in democracy scores of 0.13 [95% CI: 0.05, 0.21] scale points on average (10th percentile: 0.55 [95% CI: 0.51, 0.60], 90th percentile: 0.68 [0.63, 0.73]). This still represents a fairly important difference. <a href="https://www.cogitatiopress.com/politicsandgovernance/article/view/1214" target="_blank">Lührmann, Tannenberg, and Lindberg</a>, for instance, recommend using 0.5 as the cut off between democratic and non-democratic countries. Moving from a country with very little female representation to one with a comparatively high level (but equivalent values on the other predictor variables) thus represents a change from countries straddling the democracy/non-democracy line to ones that are more consistently democratic in nature.</p>
</blockquote>
</section>
<section id="logistic-model" class="level2 page-columns page-full" data-number="13.5">
<h2 data-number="13.5" class="anchored" data-anchor-id="logistic-model"><span class="header-section-number">13.5</span> Logistic Model</h2>
<p>The foregoing all goes for logistic regression but perhaps double so since logistic coefficients are basically uninterpretable on their own. We thus should be especially keen to use our model by calculated predicted probabilities and average marginal effects (i.e., the average change in the probability that Y = 1 given a one unit change in X). At the same time, a discussion of predicted probabilities might be helped here by the fact that 0.5 is a clear change in status: from less likely than not that Y= 1 to more likely than not.</p>
<div class="cell" data-tbl-cap-location="top">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="annotated-cell-15"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-15-1"><a href="#annotated-cell-15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data management</span></span>
<span id="annotated-cell-15-2"><a href="#annotated-cell-15-2" aria-hidden="true" tabindex="-1"></a>demdata <span class="ot">&lt;-</span> demdata <span class="sc">|&gt;</span> </span>
<span id="annotated-cell-15-3"><a href="#annotated-cell-15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="annotated-cell-15-4"><a href="#annotated-cell-15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">dem_decrease =</span> <span class="fu">factor</span>(dem_decrease, </span>
<span id="annotated-cell-15-5"><a href="#annotated-cell-15-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), </span>
<span id="annotated-cell-15-6"><a href="#annotated-cell-15-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Stable/Increased Democracy"</span>, </span>
<span id="annotated-cell-15-7"><a href="#annotated-cell-15-7" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"Decreased Democracy"</span>)), </span>
<span id="annotated-cell-15-8"><a href="#annotated-cell-15-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">cvoting =</span> <span class="fu">factor</span>(compulsory_voting, </span>
<span id="annotated-cell-15-9"><a href="#annotated-cell-15-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), </span>
<span id="annotated-cell-15-10"><a href="#annotated-cell-15-10" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No Compulsory Voting"</span>, </span>
<span id="annotated-cell-15-11"><a href="#annotated-cell-15-11" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Compulsory Voting"</span>)))</span>
<span id="annotated-cell-15-12"><a href="#annotated-cell-15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-15-13"><a href="#annotated-cell-15-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Model</span></span>
<span id="annotated-cell-15-14"><a href="#annotated-cell-15-14" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(dem_decrease <span class="sc">~</span> Facebook <span class="sc">+</span> cpi <span class="sc">+</span> cvoting, </span>
<span id="annotated-cell-15-15"><a href="#annotated-cell-15-15" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> demdata, </span>
<span id="annotated-cell-15-16"><a href="#annotated-cell-15-16" aria-hidden="true" tabindex="-1"></a>          <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="annotated-cell-15-17"><a href="#annotated-cell-15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-15-18"><a href="#annotated-cell-15-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Table (including Nagelkerke R2)</span></span>
<span id="annotated-cell-15-19"><a href="#annotated-cell-15-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-15-20"><a href="#annotated-cell-15-20" aria-hidden="true" tabindex="-1"></a><span class="co"># adding Nagelkerke R2</span></span>
<span id="annotated-cell-15-21"><a href="#annotated-cell-15-21" aria-hidden="true" tabindex="-1"></a>dem_model_2 <span class="ot">&lt;-</span> <span class="fu">modelsummary</span>(m2, </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-15" data-target-annotation="1">1</button><span id="annotated-cell-15-22" class="code-annotation-target"><a href="#annotated-cell-15-22" aria-hidden="true" tabindex="-1"></a>                            <span class="at">output =</span> <span class="st">'modelsummary_list'</span>)</span>
<span id="annotated-cell-15-23"><a href="#annotated-cell-15-23" aria-hidden="true" tabindex="-1"></a></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-15" data-target-annotation="2">2</button><span id="annotated-cell-15-24" class="code-annotation-target"><a href="#annotated-cell-15-24" aria-hidden="true" tabindex="-1"></a>dem_model_2<span class="sc">$</span>glance<span class="sc">$</span>r2.nagelkerke <span class="ot">&lt;-</span> performance<span class="sc">::</span><span class="fu">r2_nagelkerke</span>(m2)</span>
<span id="annotated-cell-15-25"><a href="#annotated-cell-15-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-15-26"><a href="#annotated-cell-15-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-15-27"><a href="#annotated-cell-15-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating the table</span></span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-15" data-target-annotation="3">3</button><span id="annotated-cell-15-28" class="code-annotation-target"><a href="#annotated-cell-15-28" aria-hidden="true" tabindex="-1"></a>dem_tab_2 <span class="ot">&lt;-</span> <span class="fu">modelsummary</span>(dem_model_2,</span>
<span id="annotated-cell-15-29"><a href="#annotated-cell-15-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimate =</span> <span class="st">"{estimate}{stars}</span><span class="sc">\n</span><span class="st">({std.error})"</span>, </span>
<span id="annotated-cell-15-30"><a href="#annotated-cell-15-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">statistic =</span> <span class="cn">NULL</span>, </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-15" data-target-annotation="4">4</button><span id="annotated-cell-15-31" class="code-annotation-target"><a href="#annotated-cell-15-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">gof_map =</span> <span class="fu">c</span>(<span class="st">"nobs"</span>, <span class="st">"r2.nagelkerke"</span>),</span>
<span id="annotated-cell-15-32"><a href="#annotated-cell-15-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">coef_rename =</span> <span class="fu">c</span>(</span>
<span id="annotated-cell-15-33"><a href="#annotated-cell-15-33" aria-hidden="true" tabindex="-1"></a>               <span class="st">'(Intercept)'</span> <span class="ot">=</span> <span class="st">'Intercept'</span>, </span>
<span id="annotated-cell-15-34"><a href="#annotated-cell-15-34" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Facebook"</span> <span class="ot">=</span> <span class="st">"Facebook Members (%) in 2013"</span>, </span>
<span id="annotated-cell-15-35"><a href="#annotated-cell-15-35" aria-hidden="true" tabindex="-1"></a>               <span class="st">"cpi"</span> <span class="ot">=</span> <span class="st">"Corruption Perception Index"</span>, </span>
<span id="annotated-cell-15-36"><a href="#annotated-cell-15-36" aria-hidden="true" tabindex="-1"></a>               <span class="st">"cvotingCompulsory Voting"</span> <span class="ot">=</span> <span class="st">"Compulsory Voting System"</span>),</span>
<span id="annotated-cell-15-37"><a href="#annotated-cell-15-37" aria-hidden="true" tabindex="-1"></a>             <span class="at">notes =</span> <span class="fu">list</span>(<span class="st">"Notes: Logit Coefficients with standard errors in parentheses"</span>, </span>
<span id="annotated-cell-15-38"><a href="#annotated-cell-15-38" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"* p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001"</span>), </span>
<span id="annotated-cell-15-39"><a href="#annotated-cell-15-39" aria-hidden="true" tabindex="-1"></a>             <span class="at">output =</span> <span class="st">'flextable'</span> )</span>
<span id="annotated-cell-15-40"><a href="#annotated-cell-15-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-15-41"><a href="#annotated-cell-15-41" aria-hidden="true" tabindex="-1"></a>dem_tab_2 <span class="ot">&lt;-</span> dem_tab_2 <span class="sc">|&gt;</span> </span>
<span id="annotated-cell-15-42"><a href="#annotated-cell-15-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hline</span>(<span class="at">i =</span> <span class="fu">nrow_part</span>(dem_tab_2) <span class="sc">-</span> <span class="dv">2</span>) <span class="sc">|&gt;</span>  </span>
<span id="annotated-cell-15-43"><a href="#annotated-cell-15-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">align</span>(<span class="at">i =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow_part</span>(dem_tab_2), <span class="at">j =</span> <span class="dv">2</span><span class="sc">:</span><span class="fu">ncol_keys</span>(dem_tab_2), </span>
<span id="annotated-cell-15-44"><a href="#annotated-cell-15-44" aria-hidden="true" tabindex="-1"></a>        <span class="at">align =</span> <span class="st">'center'</span>) <span class="sc">|&gt;</span>  </span>
<span id="annotated-cell-15-45"><a href="#annotated-cell-15-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">align</span>(<span class="at">align =</span> <span class="st">'center'</span>, <span class="at">part =</span> <span class="st">'header'</span>) <span class="sc">|&gt;</span> </span>
<span id="annotated-cell-15-46"><a href="#annotated-cell-15-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autofit</span>() </span>
<span id="annotated-cell-15-47"><a href="#annotated-cell-15-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-15-48"><a href="#annotated-cell-15-48" aria-hidden="true" tabindex="-1"></a>dem_tab_2</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-15" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-15" data-code-lines="22" data-code-annotation="1">The Nagelkerke R2 is not added by default. The first step in getting around this is this line. <code>output = modelsummary_list</code> tells the command to simply export the underlying data that will be used in creating the table. We can then add new data before creating the table. No other formatting options should be used yet.</span>
</dd>
<dt data-target-cell="annotated-cell-15" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-15" data-code-lines="24" data-code-annotation="2"><code>output = modelsummary_list</code> creates a list with two tables: (1) <code>$tidy</code> which contains information about the coefficients, standard errors, etc. and (2) <code>$glance</code> which contains information about model fit. This line adds a new column to that table called “r2.nagelkerke” that will contain the output of the <code>r2_nagelkerke</code> command from the <code>performance</code> package. The naming here is important: it needs to be “rs.nagelkerke” for the table to use the correct output.</span>
</dd>
<dt data-target-cell="annotated-cell-15" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-15" data-code-lines="28" data-code-annotation="3">We then create the table but here we use the name of the object we created using <code>modelsummary_list</code> and which has the extra column from step 2.</span>
</dd>
<dt data-target-cell="annotated-cell-15" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-15" data-code-lines="31" data-code-annotation="4">And we include the Nagelkerke R2 like so.</span>
</dd>
</dl>
</div>
<div id="tbl-dem-model1" class="cell quarto-float anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dem-model1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.2: Predicting Democracy Levels: Logit Analyses
</figcaption>
<div aria-describedby="tbl-dem-model1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-be783cfc{}.cl-be6e67ea{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-be721098{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-be7210a2{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-be7224de{width:2.459in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-be7224e8{width:0.786in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-be7224f2{width:2.459in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-be7224f3{width:0.786in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-be7224fc{width:2.459in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-be722506{width:0.786in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-be722507{width:2.459in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-be722508{width:0.786in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-be722510{width:2.459in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-be722511{width:0.786in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-be72251a{width:2.459in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-be72251b{width:0.786in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-be722524{width:2.459in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-be72252e{width:0.786in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-be783cfc"><thead><tr style="overflow-wrap:break-word;"><th class="cl-be7224de"><p class="cl-be721098"><span class="cl-be6e67ea"> </span></p></th><th class="cl-be7224e8"><p class="cl-be721098"><span class="cl-be6e67ea">(1)</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-be7224f2"><p class="cl-be7210a2"><span class="cl-be6e67ea">Intercept</span></p></td><td class="cl-be7224f3"><p class="cl-be721098"><span class="cl-be6e67ea">1.078*</span><br><span class="cl-be6e67ea">(0.481)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-be7224f2"><p class="cl-be7210a2"><span class="cl-be6e67ea">Facebook Members (%) in 2013</span></p></td><td class="cl-be7224f3"><p class="cl-be721098"><span class="cl-be6e67ea">0.046**</span><br><span class="cl-be6e67ea">(0.015)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-be7224fc"><p class="cl-be7210a2"><span class="cl-be6e67ea">Corruption Perception Index</span></p></td><td class="cl-be722506"><p class="cl-be721098"><span class="cl-be6e67ea">-0.033*</span><br><span class="cl-be6e67ea">(0.014)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-be722507"><p class="cl-be7210a2"><span class="cl-be6e67ea">Compulsory Voting System</span></p></td><td class="cl-be722508"><p class="cl-be721098"><span class="cl-be6e67ea">0.103</span><br><span class="cl-be6e67ea">(0.540)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-be722510"><p class="cl-be7210a2"><span class="cl-be6e67ea">Num.Obs.</span></p></td><td class="cl-be722511"><p class="cl-be721098"><span class="cl-be6e67ea">155</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-be72251a"><p class="cl-be7210a2"><span class="cl-be6e67ea">R2 Nagelkerke</span></p></td><td class="cl-be72251b"><p class="cl-be721098"><span class="cl-be6e67ea">0.10</span></p></td></tr></tbody><tfoot><tr style="overflow-wrap:break-word;"><td colspan="2" class="cl-be722524"><p class="cl-be7210a2"><span class="cl-be6e67ea">Notes: Logit Coefficients with standard errors in parentheses</span></p></td></tr><tr style="overflow-wrap:break-word;"><td colspan="2" class="cl-be722524"><p class="cl-be7210a2"><span class="cl-be6e67ea">* p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</span></p></td></tr></tfoot></table></div>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-dem-model1" class="quarto-xref">Table&nbsp;<span>13.2</span></a> is our example model here. The DV again focuses on democracy score data, but here dichotomized such that countries with a score of 1 saw a <em>decrease</em> in their democracy score between 2010 and 2020 and those with a score of 0 saw either an increase or no change at all. Three IVs are included: (1) the % of people using Facebook in the country as of 2013, (2) the corruption perception index for the country (higher = <em>less</em> perceived corruption, and (3) a binary indicator for whether the country has a compulsory voting system (=1) or not (=0).</p>
<p>The coefficients here are on the log of the odds scale. We can use them to discuss the direction of the relationship but not the substance.</p>
<p>Let’s start with the compulsory voting measure. It has a positive coefficient, which indicates that countries with a compulsory voting system were more likely to see a decrease in democracy from 2010 to 2020, but this difference is not statistically significant so we cannot rule out the possibility of no difference on the DV between these categories. We could perhaps stop there as it were, i.e., simply note that we do not find a significant difference. Sometimes that is just fine in the paper. However, I think we should still calculate the predicted probability that DV = 1 (democratic decline) for both categories and their associated uncertainty in this instance. We only have 155 observations in the data. Meanwhile, very few countries are recorded as having a compulsory voting system of some type.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> Perhaps there is a meaningless expected difference between countries…or perhaps there is a large difference with lots of uncertainty.</p>
<div class="no-row-height column-margin column-container"><div id="fn10"><p><sup>10</sup>&nbsp;This is a slight understatement. The data here comes from the <code>v2elcomvot</code> in the V-Dem data. This variable divided countries into four categories: No CV (n = 156), CV but without sanctions or sanctions are not enforced (n = 12), CV with enforced but minimal sanctions (n = 10), and Sanctions with considerable enforced sanctions (n = 1). Really, there are perhaps 11 countries, or perhaps even 1, with a true compulsory voting system.</p></div></div><div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(demdata<span class="sc">$</span>compulsory_voting)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
156  23 </code></pre>
</div>
</div>
<p>Let’s take a look at the predicted probabilities and the average marginal effect:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicted Probability</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predictions</span>(m2, </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="st">"cvoting"</span>, </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">newdata =</span> <span class="st">"mean"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
              cvoting Estimate Pr(&gt;|z|)   S 2.5 % 97.5 % Facebook  cpi
 Compulsory Voting       0.657  0.18972 2.4 0.420  0.835     19.8 44.2
 No Compulsory Voting    0.633  0.00421 7.9 0.543  0.715     19.8 44.2

Columns: rowid, cvoting, estimate, p.value, s.value, conf.low, conf.high, Facebook, cpi, dem_decrease 
Type:  invlink(link) </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># AME</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_slopes</span>(m2, <span class="at">variables =</span> <span class="st">"cvoting"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Term                                 Contrast Estimate Std. Error     z
 cvoting Compulsory Voting - No Compulsory Voting   0.0223      0.116 0.192
 Pr(&gt;|z|)   S  2.5 % 97.5 %
    0.848 0.2 -0.205  0.249

Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
Type:  response </code></pre>
</div>
</div>
<p>Yeah, it’s not an uncertainty issue. The AME is 0.02 or a .2 percentage point difference. The predicted probabilities bring this home: Pr(Decline given compulsory voting system) = 0.66 [0.42, 0.84], Pr(Decline given non-compulsory system) = 0.63 [0.54, 0.72]. There is a lot of uncertainty around those estimates, particularly for the compulsory voting prediction, but this seems like a case where statistical insignificance is likely associated with substantive <em>insignificance</em> (at least, based on this model).</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predictions</span>(m2, </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="st">"cvoting"</span>, </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">newdata =</span> <span class="st">"mean"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> cvoting, <span class="at">y =</span> estimate)) <span class="sc">+</span> </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> conf.low, <span class="at">ymax =</span> conf.high)) <span class="sc">+</span> </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(estimate, <span class="dv">2</span>)), <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Compulsory Voting?"</span>, </span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Predicted Probability of Democratic Decline"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_discussion_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>How might we write this up?</p>
<blockquote class="blockquote">
<p>I argued in Hypothesis 1 that countries with a compulsory voting system should be less likely to experience democratic erosion. Table 1 provides the results from my logistic model testing this proposition where a negative coefficient for the compulsory voting indicator would be consistent with Hypothesis 1. Ultimately, I do not find evidence in line with my expectations. The coefficient for compulsory voting is <em>positive</em> rather than negative. It is also statistically insignificant (p = 0.85). The predicted probability of democracy scores decreasing is nearly the same in both sets of countries when covariates are set at their mean or mode (Compulsory Voting: 0.63 [95% CI: 0.54, 0.72]; No Compulsory Voting: 0.66 [0.42, 0.84]). The resulting average marginal effect of the variable is rather trivial in nature (0.02 [-0.22, 0.26]). Compulsory voting thus appears unrelated to democratic declines, a point that I discuss in further in the Conclusion.</p>
</blockquote>
<p>Let’s turn to a continuous measure: the % of people using Facebook in the country as of 2013. Its coefficient is positive and statistically significant indicating that countries with more Facebook users were more likely to see a decrease in their democracy scores than countries with fewer Facebook users. We should be highly careful about saying this is a causal relationship of course - there are likely omitted variables here and, meanwhile, the DV is a change score from 2010 to 2020 and the IV is measured in 2013, so we likely cannot rule out the possibility that decreases in the 2010-2012 region led to more Facebook use!</p>
<p>This is a continuous variable. Here, I’d recommend including a plot of the predicted probabilities and then supplementing with a discussion in text, perhaps calling attention to “low” vs “high” comparisons of relevance/interest.</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-20"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-20-1"><a href="#annotated-cell-20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Range of variable among observations in model </span></span>
<span id="annotated-cell-20-2"><a href="#annotated-cell-20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predictions</span>(m2) <span class="sc">|&gt;</span> </span>
<span id="annotated-cell-20-3"><a href="#annotated-cell-20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span> </span>
<span id="annotated-cell-20-4"><a href="#annotated-cell-20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Facebook) <span class="sc">|&gt;</span> </span>
<span id="annotated-cell-20-5"><a href="#annotated-cell-20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span>
<span id="annotated-cell-20-6"><a href="#annotated-cell-20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-20-7"><a href="#annotated-cell-20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicted Values</span></span>
<span id="annotated-cell-20-8"><a href="#annotated-cell-20-8" aria-hidden="true" tabindex="-1"></a>predvals_facebook <span class="ot">&lt;-</span> <span class="fu">predictions</span>(m2, </span>
<span id="annotated-cell-20-9"><a href="#annotated-cell-20-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">newdata =</span> <span class="fu">datagrid</span>(<span class="at">Facebook =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="fl">19.83</span>, <span class="dv">35</span>, <span class="dv">68</span>)))</span>
<span id="annotated-cell-20-10"><a href="#annotated-cell-20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-20-11"><a href="#annotated-cell-20-11" aria-hidden="true" tabindex="-1"></a>predvals_facebook</span>
<span id="annotated-cell-20-12"><a href="#annotated-cell-20-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-20-13"><a href="#annotated-cell-20-13" aria-hidden="true" tabindex="-1"></a><span class="co"># AME</span></span>
<span id="annotated-cell-20-14"><a href="#annotated-cell-20-14" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_slopes</span>(m2, <span class="at">variables =</span> <span class="st">"Facebook"</span>)</span>
<span id="annotated-cell-20-15"><a href="#annotated-cell-20-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-20-16"><a href="#annotated-cell-20-16" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot</span></span>
<span id="annotated-cell-20-17"><a href="#annotated-cell-20-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(predvals_facebook, <span class="fu">aes</span>(<span class="at">x =</span> Facebook, <span class="at">y =</span> estimate)) <span class="sc">+</span></span>
<span id="annotated-cell-20-18"><a href="#annotated-cell-20-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="annotated-cell-20-19"><a href="#annotated-cell-20-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> conf.low, <span class="at">ymax =</span> conf.high), </span>
<span id="annotated-cell-20-20"><a href="#annotated-cell-20-20" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span> </span>
<span id="annotated-cell-20-21"><a href="#annotated-cell-20-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="annotated-cell-20-22"><a href="#annotated-cell-20-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"% Facebook Membership (2003)"</span>, </span>
<span id="annotated-cell-20-23"><a href="#annotated-cell-20-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Predicted Probability of Democratic Decline (2010-2020)"</span>) <span class="sc">+</span> </span>
<button class="code-annotation-anchor" data-target-cell="annotated-cell-20" data-target-annotation="1">1</button><span id="annotated-cell-20-24" class="code-annotation-target"><a href="#annotated-cell-20-24" aria-hidden="true" tabindex="-1"></a>  ggpubr<span class="sc">::</span><span class="fu">theme_pubclean</span>()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-hidden code-annotation-container-grid">
<dt data-target-cell="annotated-cell-20" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-20" data-code-lines="24" data-code-annotation="1">Uses a <code>ggplot()</code> theme contained in the <code>ggpubr</code> package. That package would need to be installed for the syntax to work. Just showing some different options here.</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_discussion_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    Facebook    
 Min.   : 0.00  
 1st Qu.: 3.00  
 Median :15.00  
 Mean   :19.83  
 3rd Qu.:35.00  
 Max.   :68.00  

 Facebook Estimate Pr(&gt;|z|)    S 2.5 % 97.5 %  cpi              cvoting
      0.0    0.407  0.23428  2.1 0.270  0.560 44.2 No Compulsory Voting
      3.0    0.441  0.39851  1.3 0.314  0.577 44.2 No Compulsory Voting
     19.8    0.633  0.00421  7.9 0.543  0.715 44.2 No Compulsory Voting
     35.0    0.777  &lt; 0.001 12.3 0.643  0.871 44.2 No Compulsory Voting
     68.0    0.942  &lt; 0.001 10.7 0.768  0.988 44.2 No Compulsory Voting

Columns: rowid, estimate, p.value, s.value, conf.low, conf.high, cpi, cvoting, Facebook, dem_decrease 
Type:  invlink(link) 

     Term Estimate Std. Error   z Pr(&gt;|z|)    S   2.5 % 97.5 %
 Facebook   0.0101    0.00297 3.4   &lt;0.001 10.5 0.00427 0.0159

Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
Type:  response </code></pre>
</div>
</div>
<p>The probability of a democratic decline given a one unit change in the Facebook measure is around 0.01 probability points, on average. The predicted values (plot) shows that the degree of change when moving a significant degree of the range of the IV is also pretty substantial. The probability when we’re at the minimum of the IV is around 0.41 [0.27, 0.56] but 0.94 [0.77, 0.99] at its maximum. Of course, that maximum value might not be the best one to focus on much like earlier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Uses predictions() to just get observations in the model</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predictions</span>(m2) <span class="sc">|&gt;</span> </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Facebook)) <span class="sc">+</span> </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">'black'</span>, <span class="at">fill =</span> <span class="st">'white'</span>) <span class="sc">+</span> </span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">25</span>, <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">70</span>, <span class="at">by =</span> <span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_discussion_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predictions</span>(m2) <span class="sc">|&gt;</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Facebook) <span class="sc">|&gt;</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Facebook    
 Min.   : 0.00  
 1st Qu.: 3.00  
 Median :15.00  
 Mean   :19.83  
 3rd Qu.:35.00  
 Max.   :68.00  </code></pre>
</div>
</div>
<p>While there are lots of countries in the data that had no Facebook users in 2013, there is only one at the very maximum. This country is also a bit extreme when compared to the next closest ones which are at around 50-55 on the variable. Much as above, we can perhaps think about some other comparisons that might be more informative:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 10th and 90th percentile</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(demdata<span class="sc">$</span>Facebook, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.9</span>), </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">na.rm =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>10% 90% 
  1  47 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predictions</span>(m2, <span class="at">newdata =</span> <span class="fu">datagrid</span>(<span class="at">Facebook =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">47</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Facebook Estimate Pr(&gt;|z|)    S 2.5 % 97.5 %  cpi              cvoting
        1    0.419    0.278  1.8 0.284  0.566 44.2 No Compulsory Voting
       47    0.859   &lt;0.001 11.6 0.695  0.942 44.2 No Compulsory Voting

Columns: rowid, estimate, p.value, s.value, conf.low, conf.high, cpi, cvoting, Facebook, dem_decrease 
Type:  invlink(link) </code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">comparisons</span>(m2, </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">variables =</span> <span class="fu">list</span>(<span class="at">Facebook =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">47</span>)), </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">newdata =</span> <span class="st">'mean'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Term Contrast Estimate Std. Error    z Pr(&gt;|z|)    S 2.5 % 97.5 % Facebook
 Facebook   47 - 1    0.441      0.117 3.76   &lt;0.001 12.5 0.211   0.67     19.8
  cpi              cvoting
 44.2 No Compulsory Voting

Columns: rowid, term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted, Facebook, cpi, cvoting, dem_decrease 
Type:  response </code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SD &lt; Mean vs. SD &gt; Mean</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Stores the values first so I don't have to look them up and manually add them</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>mean_below <span class="ot">&lt;-</span> <span class="fu">mean</span>(demdata<span class="sc">$</span>Facebook, <span class="at">na.rm =</span> T) <span class="sc">-</span> <span class="fu">sd</span>(demdata<span class="sc">$</span>Facebook, <span class="at">na.rm =</span> T)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>mean_above <span class="ot">&lt;-</span> <span class="fu">mean</span>(demdata<span class="sc">$</span>Facebook, <span class="at">na.rm =</span> T) <span class="sc">+</span> <span class="fu">sd</span>(demdata<span class="sc">$</span>Facebook, <span class="at">na.rm =</span> T)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="fu">predictions</span>(m2, <span class="at">newdata =</span> <span class="fu">datagrid</span>(<span class="at">Facebook =</span> <span class="fu">c</span>(mean_below, mean_above)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Facebook Estimate Pr(&gt;|z|)    S 2.5 % 97.5 %  cpi              cvoting
     1.94    0.429    0.329  1.6 0.298  0.571 44.2 No Compulsory Voting
    38.07    0.801   &lt;0.001 12.1 0.658  0.894 44.2 No Compulsory Voting

Columns: rowid, estimate, p.value, s.value, conf.low, conf.high, cpi, cvoting, Facebook, dem_decrease 
Type:  invlink(link) </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">comparisons</span>(m2, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">variables =</span> <span class="fu">list</span>(<span class="at">Facebook =</span> <span class="fu">c</span>(mean_below, mean_above)), </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">newdata =</span> <span class="st">'mean'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Term                            Contrast Estimate Std. Error    z Pr(&gt;|z|)
 Facebook 38.0687601647005 - 1.94397868880272    0.372      0.109 3.41   &lt;0.001
    S 2.5 % 97.5 % Facebook  cpi              cvoting
 10.6 0.158  0.586     19.8 44.2 No Compulsory Voting

Columns: rowid, term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted, Facebook, cpi, cvoting, dem_decrease 
Type:  response </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 0% vs. Median</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predictions</span>(m2, <span class="at">newdata =</span> <span class="fu">datagrid</span>(<span class="at">Facebook =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">15</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Facebook Estimate Pr(&gt;|z|)   S 2.5 % 97.5 %  cpi              cvoting
        0    0.407   0.2343 2.1 0.270  0.560 44.2 No Compulsory Voting
       15    0.580   0.0841 3.6 0.489  0.665 44.2 No Compulsory Voting

Columns: rowid, estimate, p.value, s.value, conf.low, conf.high, cpi, cvoting, Facebook, dem_decrease 
Type:  invlink(link) </code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">comparisons</span>(m2, </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">variables =</span> <span class="fu">list</span>(<span class="at">Facebook =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">15</span>)), </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">newdata =</span> <span class="st">'mean'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Term Contrast Estimate Std. Error    z Pr(&gt;|z|)   S  2.5 % 97.5 % Facebook
 Facebook   15 - 1    0.161     0.0524 3.08  0.00208 8.9 0.0586  0.264     19.8
  cpi              cvoting
 44.2 No Compulsory Voting

Columns: rowid, term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted, Facebook, cpi, cvoting, dem_decrease 
Type:  response </code></pre>
</div>
</div>
<p>We might write:</p>
<blockquote class="blockquote">
<p>I argued in Hypothesis 1 that countries with greater Facebook usage would be more likely to see a decline in their democracy scores in the years between 2010 and 2020. Table 1 provides the results from my logistic model testing this proposition where a positive coefficient for the Facebook variable would be consistent with H1. And, indeed, a positive and statistically significant (p &lt; 0.01) coefficient emerges. The corresponding average marginal effect for the Facebook variable is 0.01 [95% CI: 0.004, 0.02], which indicates that the probability of seeing a decrease in a country’s democracy score increases by 0.01 probability points with each 1% increase in Facebook membership. This expected change adds up as seen in Figure 1 which plots the predicted probability of a democratic decline (holding the other predictors at their mean or mode) across the range of the Facebook variable. The amount of change is quite substantial. For instance, the predicted probability of democratic erosion among countries one standard deviation above the mean on the Facebook variable (38.1%) is 0.372 probability points greater than among countries one standard deviation below the mean of this variable (1.94%; difference in probability: 0.37 [0.16, 0.59]). Table 1 and Figure 1 thus provide consistent evidence in favor of H1.</p>
</blockquote>


</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./analysis_rscript.html" class="pagination-link" aria-label="R Script Files">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">R Script Files</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./analysis_03.html" class="pagination-link" aria-label="Regression Table Formatting Suggestion">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Regression Table Formatting Suggestion</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>